name: rjmath
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  d3_force_flutter:
    git: https://github.com/MathGaps/d3-force-flutter.git
  katex_flutter:
    git: https://github.com/rlch/katex_flutter
  cupertino_icons: ^1.0.2
  flutter_nord_theme: ^2.1.0
  vector_math: ^2.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  flutter_font_icons: ^2.2.4
  url_launcher: ^6.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
